services:
  - type: static
    name: ayigotech
    repo: https://github.com/ayitteyg/ayigotech.git
    branch: main
    buildCommand: npm install && npm run build --configuration production
    publishDir: dist/frontend/browser
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
